FROM node:22 AS build

WORKDIR /app
COPY config/node/frontend/package.json .
RUN npm install
COPY config/node/frontend .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY config/nginx/nginx.conf /etc/nginx/conf.d/default.conf